Repository AMP-Organisation/AMP-Back, pull requests merged in 2021-03, with the labels that each got.

#4 Feat/user
  .gitignore
  app/.env
  app/core/settings.py
  app/crud/user_crud.py
  app/database/models/user_model.py
  app/main.py
  app/routers/login_route.py
  app/routers/users_route.py
  app/schemas/group_schema.py
  app/schemas/message.py
  app/schemas/user_schema.py
Labels: enhancement

#5 Feat/route maladies
  app/.env
  app/core/settings.py
  app/crud/disease_crud.py
  app/database/base_class.py
  app/database/models/disease_model.py
  app/database/session.py
  app/main.py
  app/routers/diseases_routes.py
  app/schemas/disease_schemas.py
Labels: enhancement, feature, learning

#6 Feat/place
  Pipfile
  app/core/settings.py
  app/crud/crud_place.py
  app/database/models/place_model.py
  app/main.py
  app/routers/place_route.py
  app/schemas/message_schema.py
  app/schemas/place_schema.py
  app/schemas/place_tags_schema.py
  app/schemas/place_type_schema.py
Labels: enhancement

#7 :construction: Update pipfile.lock for heroku
  Pipfile.lock
Labels: bug
